### ISSUE TITLE
Duplicate items

### ISSUE THREAD

**Issue by Lemar98** [Rysefoxx/RyseInventory#27]
**Describe the bug**
I make an inventory, in which items are added every N time. The player can take these items from the inventory, but cannot put them there.

I noticed one interesting bug and I still can't figure out if it's related to my code or if it's really a bug.

If I move a stack of items very quickly, they are somehow duplicated.

**To Reproduce**
1. run my code
2. very quickly move itemstacks

**Code (Optional)**
https://pastebin.com/wzGVjbSB

**Videos**
![ezgif com-gif-maker](https://user-images.githubusercontent.com/45980309/195176180-2d065d88-f68c-4539-b7fe-b77d8bcaabf0.gif)

**Comment by Rysefoxx** [comment]
A very funny bug. Actually, such a one is not possible from my point of view. Every time the inventory is called, your init part is called. Maybe something changes there while you keep rebuilding it?

Doesn't mean it's your bug. I'll take a look at it this weekend (No time before then, unfortunately).

**Comment by Lemar98** [comment]
I don't know what I should do to make items clone. In any case, please try to reproduce the problem with my code at a convenient time.

**Comment by Rysefoxx** [comment]
> **Describe the bug**
 I make an inventory, in which items are added every N time. The player can take these items from the inventory, but cannot put them there.

Do you think you can't place them there via "drag"? If yes you have to enable this option via #ignoreEvents

Regarding the duplicate bug, I was not able to reproduce it. Therefore I ask you to call the method #ignoreManualItems temporarily. If the error is no longer present, I would have a possible reason, if not I am back to 0.

**Comment by Lemar98** [comment]
As soon as I used #ignoreManualItems the bug was fixed

**Comment by Rysefoxx** [comment]
I wish I could. Unfortunately, no matter how many times I try, no matter what code, I am not able to reproduce your error.

I also can't make a logical connection. If you reopen the RyseInventory, the provider will be rebuilt, so a new pagination object will be created. From this point on it is impossible for something to duplicate because the new pagination had nothing to do with the other pagination object. The content that is displayed in the inventory is then defined by your provider.

The code you sent me works without problems.

I have one last idea. I see that you are calling a command every time. Is the RyseInventory always recreated there? Or do you store it in a global variable?

**Comment by Lemar98** [comment]
When the player enters a command, I check if an inventory exists with that ID. If it doesn't exist, I create it first.
https://pastebin.com/RuKiAMPZ

**Comment by Rysefoxx** [comment]
What if you recreate the inventory every time? Does the problem still exist then?

**Comment by Lemar98** [comment]
Yes. Recently, I was just creating an inventory every time the player entered a command and only today did it to try to find an existing one

**Comment by Lemar98** [comment]
Remind me, please, what does #ignoreManualItems() do?

**Comment by Rysefoxx** [comment]
If you call this method, the items that the player can put into the upper inventory will not be saved.

For example, if you say slot 0 is ignored, the player can take an item from his inventory and put it in slot 0. 

If the method was not called in this case, the item will not be saved. Since it is only a temporary item, it is also not saved in the head.

If you call the method, the item will be saved. If you change the page and go back, the item should be there again.

**Comment by Lemar98** [comment]
Every time I close the inventory, I save the items in it. I tried to print to the console a list of items that are in the inventory at the time of its closing and, for some reason, there are items that are subsequently duplicated. Although the gif shows that I can not put this item there.
https://pastebin.com/x7Zpn2gr

**Comment by Lemar98** [comment]
for some reason, #getAllData() returns me something that is not in the inventory. I'll try to experiment a little more with this later. for example, stop saving items

**Comment by Rysefoxx** [comment]
> for some reason, #getAllData() returns me something that is not in the inventory. I'll try to experiment a little more with this later. for example, stop saving items

I have tried a bit with getAllData and it works without problems.

**Comment by Lemar98** [comment]
I could not find the reason for this behavior. You will have to use #ignoreManualItems() where necessary.
