### ISSUE TITLE
Inventory click event doesn't cancelled if builder used #ignoredSlots option

### ISSUE THREAD

**Issue by Lemar98** [Rysefoxx/RyseInventory#38]
I have already described such a problem, but I still have not found a solution.

I have a custom inventory system. For some inventories, I need to make it so the player can't put items in, but can only pick them up.

Now the situation is such that if the player clicks on an item in the inventory with some item, they are swapped, thus the player was able to put a foreign item in the inventory.

No matter how hard I try, I can't cancel such a click, most likely because the #ignoredSlots() option is used in the builder.

Maybe there is some way to cancel the event if the player clicks an item on an item with #ignoredSlots() enabled?

**Comment by Rysefoxx** [comment]
> Maybe there is some way to cancel the event if the player clicks an item on an item with #ignoredSlots() enabled?

Hmm I can look that maybe you can say.
InvenetoryContents#advancedSlot(0).
.onClick(...)

#advancedSlots would then only work if you have defined the slot via #ignoredSlots. Otherwise an error occurs.
So you can prevent the event in the InventoryClickEvent Consumer.

Would this help you?
In the advancedSlot method you can then use multiple slots for the same InventoryClickEvent consumer.

**Comment by Lemar98** [comment]
To be honest, I did not fully understand you because of my bad English. Would it be hard for you to describe your sentence with some pseudo-code with an example of its behavior?

**Comment by Rysefoxx** [comment]
``> To be honest, I did not fully understand you because of my bad English. Would it be hard for you to describe your sentence with some pseudo-code with an example of its behavior?

ofc.

You say e.g. slot 0 is ignored. So my InventoryClickEvent will never interrupt anything. You can then specify the slot with #advancedSlot and add your own logic. In my case, if the player has an item on the cursor, the InventoryClickEvent is stopped. That means it will not be swapped. If the player has no item on the cursor, he can take the item out of the inventory without problems.

```java
        RyseInventory.builder()
                .title("a")
                .rows(6)
                .ignoredSlots(0)
                .provider(new InventoryProvider() {
                    @Override
                    public void init(Player player, InventoryContents contents) {
                        contents.advancedSlot(0).onClick(event -> {
                            if(event.getCursor() != null && event.getCursor().getType() != Material.AIR) {
                                event.setCancelled(true);
                                return;
                            }
                        });
                        
                    }
                })
                .build(this)
                .openAll();

**Comment by Lemar98** [comment]
Is it possible to add this method to the builder?

**Comment by Rysefoxx** [comment]
You mean this way?

```java
        RyseInventory.builder()
                .title("a")
                .rows(6)
                .ignoredSlots(0, event -> {
                    if (event.getCursor() != null && event.getCursor().getType() != Material.AIR) {
                        event.setCancelled(true);
                        return;
                    }
                })
                .provider(new InventoryProvider() {
                    @Override
                    public void init(Player player, InventoryContents contents) {
                    }
                })
                .build(this)
                .openAll();

**Comment by Lemar98** [comment]
Yes
It would be great if both methods were implemented

**Comment by Rysefoxx** [comment]
[Update v1.5.3](https://github.com/Rysefoxx/RyseInventory/releases/tag/v1.5.3)

Attention! The GroupId has changed. Please report errors.
