### ISSUE TITLE
Can't use player heads. (base64 / UUID / name) + slide animation

### ISSUE THREAD

**Issue by No1Evil** [Rysefoxx/RyseInventory#4]
Hello, I ran into a problem with heads. If i use .skullFrom(UUID / base  64 / name) it shows the simple player head in any way.
For example:
`pattern.set('B', IntelligentItem.empty(new ItemBuilder(Material.PLAYER_HEAD)
                                .skullFromUuid(player.getUniqueId())
                                .displayName("Example")
                                .build()));`

`pattern.set('B', IntelligentItem.empty(new ItemBuilder(Material.PLAYER_HEAD)
.skullFrombase64("eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDBmMmRkZDNjMTYyZDZjNzdhNDIwNzYyNWRiMmU2NTYwMzZmMzZmNDkyYmVlNzdmMWU4NjljZDZjYWQyYmFkNSJ9fX0=")
                                .displayName("Example")
                                .build()));`

Furthermore, inventory slide animation is not working for me without any errors. I used the wiki example.

RyseInventory version: 1.3.4
RyseInventory is shaded into my plugin.

Thanks in advance.

**Comment by Rysefoxx** [comment]
Hey, thanks for the bug report

Regarding problem 1:
It looks like you are using the ItemBuilder in RyseInventory. The ItemBuilder should never be usable for users (due to the fact that it was only used for testing and is not complete).

Regarding problem 2:
Correct the animation did not work anymore, due to restructuring in RyseInventory. This bug will be fixed in update 1.3.5.

1.3.5 is coming out any moment.

**Comment by No1Evil** [comment]
Thx

**Comment by Rysefoxx** [comment]
Update 1.3.5 is out.

[Changelog](https://github.com/Rysefoxx/RyseInventory/releases/tag/v1.3.5)

**Comment by Rysefoxx** [comment]
Update 1.3.6 is rolling out now because I accidentally forgot some animation types.
