### ISSUE TITLE
Pagination#lastPage is always 0 / Pagination#isLast is always true

### ISSUE THREAD

**Issue by Wupin** [Rysefoxx/RyseInventory#41]
**Describe the bug**
Pagination#lastPage is always 0 / Pagination#isLast is always true

**To Reproduce**
Just create a pagination menu

**Expected behavior**
not be 0 / true

**Code (Optional)**
https://pastebin.com/QDLtsKf6

**Screenshots**
https://prnt.sc/LDszW5iJb-YR

**Comment by Rysefoxx** [comment]
That makes sense, you can't give a presentation if you haven't studied the subject.

It is the same with RyseInventory. Your isLast call doesn't make much sense, because you only put something into the pagination via #addItem afterwards.

Try to put the items into the pagination first and then call isLast. If the problem still exists, report it once.

**Comment by Wupin** [comment]
My fault it's working, thanks for the help!
